class PermissionModel {
  String id, group_id;
  String products_index,
      products_add,
      products_edit,
      products_delete,
      products_cost,
      products_price,
      sales_index,
      sales_add,
      sales_edit,
      quotes_delete,
      quotes_email,
      quotes_edit,
      quotes_pdf,
      quotes_add,
      quotes_index,
      sales_pdf,
      sales_email,
      sales_delete,
      purchases_index,
      purchases_add,
      purchases_edit,
      purchases_pdf,
      purchases_email,
      purchases_delete,
      transfers_index,
      transfers_add,
      transfers_edit,
      transfers_pdf,
      transfers_email,
      transfers_delete,
      customers_index,
      customers_add,
      customers_edit,
      customers_delete,
      suppliers_index,
      suppliers_add,
      suppliers_edit,
      suppliers_delete,
      sales_deliveries,
      sales_add_delivery,
      sales_edit_delivery,
      sales_delete_delivery,
      sales_email_delivery,
      sales_pdf_delivery,
      sales_gift_cards,
      sales_add_gift_card,
      sales_edit_gift_card,
      sales_delete_gift_card,
      pos_index,
      sales_return_sales,
      reports_index,
      reports_warehouse_stock,
      reports_quantity_alerts,
      reports_expiry_alerts,
      reports_products,
      reports_daily_sales,
      reports_monthly_sales,
      reports_sales,
      reports_payments,
      reports_purchases,
      reports_profit_loss,
      reports_customers,
      reports_suppliers,
      reports_staff,
      reports_register,
      sales_payments,
      purchases_payments,
      purchases_expenses,
      products_adjustments,
      bulk_actions,
      customers_deposits,
      customers_delete_deposit,
      products_barcode,
      purchases_return_purchases,
      reports_expenses,
      reports_daily_purchases,
      reports_monthly_purchases,
      products_stock_count,
      edit_price,
      returns_index,
      returns_add,
      returns_edit,
      returns_delete,
      returns_email,
      returns_pdf,
      reports_tax;

  PermissionModel(
      {required this.id,
      required this.group_id,
      required this.bulk_actions,
      required this.customers_add,
      required this.customers_delete,
      required this.customers_delete_deposit,
      required this.customers_deposits,
      required this.customers_edit,
      required this.customers_index,
      required this.edit_price,
      required this.pos_index,
      required this.products_add,
      required this.products_adjustments,
      required this.products_barcode,
      required this.products_cost,
      required this.products_delete,
      required this.products_edit,
      required this.products_index,
      required this.products_price,
      required this.products_stock_count,
      required this.purchases_add,
      required this.purchases_delete,
      required this.purchases_edit,
      required this.purchases_email,
      required this.purchases_expenses,
      required this.purchases_index,
      required this.purchases_payments,
      required this.purchases_pdf,
      required this.purchases_return_purchases,
      required this.quotes_add,
      required this.quotes_delete,
      required this.quotes_edit,
      required this.quotes_email,
      required this.quotes_index,
      required this.quotes_pdf,
      required this.reports_customers,
      required this.reports_daily_purchases,
      required this.reports_daily_sales,
      required this.reports_expenses,
      required this.reports_expiry_alerts,
      required this.reports_index,
      required this.reports_monthly_purchases,
      required this.reports_monthly_sales,
      required this.reports_payments,
      required this.reports_products,
      required this.reports_profit_loss,
      required this.reports_purchases,
      required this.reports_quantity_alerts,
      required this.reports_register,
      required this.reports_sales,
      required this.reports_staff,
      required this.reports_suppliers,
      required this.reports_tax,
      required this.reports_warehouse_stock,
      required this.returns_add,
      required this.returns_delete,
      required this.returns_edit,
      required this.returns_email,
      required this.returns_index,
      required this.returns_pdf,
      required this.sales_add,
      required this.sales_add_delivery,
      required this.sales_add_gift_card,
      required this.sales_delete,
      required this.sales_delete_delivery,
      required this.sales_delete_gift_card,
      required this.sales_deliveries,
      required this.sales_edit,
      required this.sales_edit_delivery,
      required this.sales_edit_gift_card,
      required this.sales_email,
      required this.sales_email_delivery,
      required this.sales_gift_cards,
      required this.sales_index,
      required this.sales_payments,
      required this.sales_pdf,
      required this.sales_pdf_delivery,
      required this.sales_return_sales,
      required this.suppliers_add,
      required this.suppliers_delete,
      required this.suppliers_edit,
      required this.suppliers_index,
      required this.transfers_add,
      required this.transfers_delete,
      required this.transfers_edit,
      required this.transfers_email,
      required this.transfers_index,
      required this.transfers_pdf});

  factory PermissionModel.fromJson(Map<dynamic, dynamic> json) {
    return PermissionModel(
        group_id: json['group_id'].toString(),
        bulk_actions: json['bulk-actions'].toString(),
        customers_add: json['customers-add'].toString(),
        customers_delete: json['customers-delete'].toString(),
        customers_delete_deposit: json['bulk-actions'].toString(),
        customers_deposits: json['customers-deposits'].toString(),
        customers_edit: json['customers-edit'].toString(),
        customers_index: json['customers-index'].toString(),
        edit_price: json['edit-price'].toString(),
        id: json['id'].toString(),
        pos_index: json['pos-index'].toString(),
        products_add: json['products-add'].toString(),
        products_adjustments: json['products-adjustments'].toString(),
        products_barcode: json['products-barcode'].toString(),
        products_cost: json['products-cost'].toString(),
        products_delete: json['products-delete'].toString(),
        products_edit: json['products-edit'].toString(),
        products_index: json['products-index'].toString(),
        products_price: json['products-price'].toString(),
        products_stock_count: json['products-stock-count'].toString(),
        purchases_add: json['purchases-add'].toString(),
        purchases_delete: json['purchases-delete'].toString(),
        purchases_edit: json['purchases-edit'].toString(),
        purchases_email: json['purchases-email'].toString(),
        purchases_expenses: json['purchases-expenses'].toString(),
        purchases_index: json['purchases-index'].toString(),
        purchases_payments: json['purchases-payments'].toString(),
        purchases_pdf: json['purchases-pdf'].toString(),
        purchases_return_purchases:
            json['purchases-return-purchases'].toString(),
        quotes_add: json['quotes-add'].toString(),
        quotes_delete: json['quotes-delete'].toString(),
        quotes_edit: json['quotes-edit'].toString(),
        quotes_email: json['quotes-email'].toString(),
        quotes_index: json['quotes-index'].toString(),
        quotes_pdf: json['quotes-pdf'].toString(),
        reports_customers: json['reports-customers'].toString(),
        reports_daily_purchases: json['reports-daily-purchases'].toString(),
        reports_daily_sales: json['reports-daily-sales'].toString(),
        reports_expenses: json['reports-expenses'].toString(),
        reports_expiry_alerts: json['reports-expiry-alerts'].toString(),
        reports_index: json['reports-index'].toString(),
        reports_monthly_purchases: json['reports-monthly-purchases'].toString(),
        reports_monthly_sales: json['reports-monthly-sales'].toString(),
        reports_payments: json['reports-payments'].toString(),
        reports_products: json['reports-products'].toString(),
        reports_profit_loss: json['reports-profit-loss'].toString(),
        reports_staff: json['reports-staff'].toString(),
        reports_suppliers: json['reports-suppliers'].toString(),
        reports_purchases: json['reports-purchases'].toString(),
        reports_warehouse_stock: json['reports-warehouse-stock'].toString(),
        returns_delete: json['returns-delete'].toString(),
        returns_edit: json['returns-edit'].toString(),
        returns_index: json['returns-index'].toString(),
        returns_email: json['returns-email'].toString(),
        returns_pdf: json['returns-pdf'].toString(),
        sales_add: json['sales-add'].toString(),
        sales_add_delivery: json['sales-add-delivery'].toString(),
        returns_add: json['returns-add'].toString(),
        sales_add_gift_card: json['sales-add-gift-card'].toString(),
        sales_delete: json['sales-delete'].toString(),
        sales_email_delivery: json['sales-email-delivery'].toString(),
        sales_index: json['sales-index'].toString(),
        sales_gift_cards: json['sales-gift-cards'].toString(),
        reports_quantity_alerts: json['reports-quantity-alerts'].toString(),
        sales_deliveries: json['sales-deliveries'].toString(),
        reports_register: json['reports-register'].toString(),
        sales_edit: json['sales-edit'].toString(),
        sales_edit_delivery: json['sales-edit-delivery'].toString(),
        reports_sales: json['reports-sales'].toString(),
        reports_tax: json['reports-tax'].toString(),
        sales_delete_delivery: json['sales-delete-delivery'].toString(),
        sales_delete_gift_card: json['sales-delete-gift-card'].toString(),
        sales_edit_gift_card: json['sales-edit-gift-card'].toString(),
        sales_email: json['sales-email'].toString(),
        sales_payments: json['sales-payments'].toString(),
        sales_pdf: json['sales-pdf'].toString(),
        sales_pdf_delivery: json['sales-pdf-delivery'].toString(),
        sales_return_sales: json['sales-return-sales'].toString(),
        suppliers_add: json['suppliers-add'].toString(),
        suppliers_delete: json['suppliers-delete'].toString(),
        suppliers_edit: json['suppliers-edit'].toString(),
        suppliers_index: json['suppliers-index'].toString(),
        transfers_add: json['transfers-add'].toString(),
        transfers_delete: json['transfers-delete'].toString(),
        transfers_edit: json['transfers-edit'].toString(),
        transfers_email: json['transfers-email'].toString(),
        transfers_index: json['transfers-index'].toString(),
        transfers_pdf: json['transfers-pdf'].toString());
  }
}
